# Generated by Django 2.1.5 on 2019-02-16 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
